### ISSUE TITLE
ONNX conversion error

### ISSUE THREAD

**Issue by Guneetkaur03** [emedvedev/attention-ocr#172] opened 2020-05-30 10:36 UTC
I am attempting to convert this model to ONNX using the tf2onnx tool. The tool can take a frozen graph or saved model as input and produce an ONNX file. Unfortunately, it fails on aocr, apparently to due the graph being invalid.

I am filing the issue here and not against tf2onnx because the error occurred in Tensorflow while attempting to import the graph that aocr export produced. Here is the error:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Node 'cond/ExpandDims' has an _output_shapes attribute inconsistent with the GraphDef for output #0: Shapes must be equal rank, but are 1 and 0`

**Comment by emedvedev** [comment] 2020-06-29 07:50
Duplicate of #138. 

This is a known issue, but unfortunately I don't have cycles (or ONNX experience) at the moment. Leaving the original one open though, in case someone wants to try and fix it.

**Closed by emedvedev** 2020-06-29 07:50 UTC

**Comment by Ram-Godavarthi** [comment] 2020-07-30 10:21
Hi @Guneetkaur03 ,

Did you solve problem of attention ocr to onnx???
