### ISSUE TITLE
Visualizing attention: magic line

### ISSUE THREAD

**Issue by cipri-tom** [emedvedev/attention-ocr#68] opened 2018-02-13 08:58 UTC
Hi,

Thank you for making the code so complete and for including the attention visualization mechanism!
2 questions and 1 small issue 😃 

Issue first:
There is a small typo in [this resize](https://github.com/emedvedev/attention-ocr/blob/0cfeacb945f78e810ebac587ab06a67e7da9d752/aocr/model/model.py#L468). It should use `(mw, mh)` in order to keep the original ratio of the image. PR for such a small thing is unnecessary, right ?

---
Q1:

I was trying to understand why for some of the last letters I don't get an attention map, and I came across this "magic" [line](https://github.com/emedvedev/attention-ocr/blob/0cfeacb945f78e810ebac587ab06a67e7da9d752/aocr/model/model.py#L478):

```python 
attention_orig = np.convolve(attention_orig, [0.199547, 0.200226, 0.200454, 0.200226, 0.199547], mode='same') 
```

I think its purpose is to keep only the most relevant columns of the attention map. Is that correct ?
I'm curious how you chose those numbers :). 

---
Q2:

Also, for me, the attention maps usually come _after_ the letter. Here are the maps for `1` and `5`:
![image_0](https://user-images.githubusercontent.com/2991890/36141116-eb283fdc-10a3-11e8-8118-837f8ce751d5.jpg) ![image_1](https://user-images.githubusercontent.com/2991890/36141118-ec7ff47e-10a3-11e8-8d5e-4371eac34e44.jpg)

It this normal? Is it because the LSTM can only decide "at the end" of the digit which one it saw ?

**Comment by emedvedev** [comment] 2018-02-13 10:32
Thanks for noticing the resizing issue! Fixed. :)

The numbers are copied from [the original model](https://github.com/da03/Attention-OCR), and to be honest, I'm not entirely sure how the authors came up with them. While most parts of that model (and all the tooling around it) have been reworked, some are left as is, including the numbers. :) Feel free to ask the authors or just tweak it yourself.

Yes, the attention maps always come after the characters in this model. I'm not 100% sure that it's the accurate output and not a shift that has to be corrected, but if the machine tells me that's how it is, then who am I to argue. ¯\_(ツ)_/¯

Feel free to propose changes to visualizations! They _could_ use some work.

Closing, because the original issue has been fixed, but feel free to just use it as a comment thread. :)

**Closed by emedvedev** 2018-02-13 10:32 UTC

**Comment by reidjohnson** [comment] 2018-02-15 03:14
I don't believe the attentions should generally be offset. I've worked extensively to update the attention visualizations in my own fork, and found that the current method doesn't properly account for how images are resized. See the expected behavior below in predicting the output `1078`. I'll submit a pull request with my changes as time permits. In the meantime, keep up the good work!

![example](https://user-images.githubusercontent.com/4712548/36238982-1c57ab16-11bb-11e8-9f8e-8ec738456e55.jpg)
