### ISSUE TITLE
Exporting saved Model bug

### ISSUE THREAD

**Issue by kspook** [emedvedev/attention-ocr#140] opened 2019-07-03 00:46 UTC
Somebody knows the solution of the difference b/  saved_model and script.

If I train with the basic settings, it returns the same result b/ the saved model  and script.
But with the full-ascii training, it returns the different result.

code : https://github.com/kspook/aocr_fullascii.git
saved model/ checkpoints  : https://drive.google.com/open?id=1FsRonnoMG9cS9npIbob5F2Pgu29JyAzi

![image](https://user-images.githubusercontent.com/36400753/60235548-1fcc6d80-98e3-11e9-814c-f3e5ca7fbc3e.png)

![image](https://user-images.githubusercontent.com/36400753/60239481-dc74fd80-98e8-11e9-837c-32c000a18102.png)

**Comment by emedvedev** [comment] 2019-07-03 01:11
Duplicate of https://github.com/emedvedev/attention-ocr/issues/135.

**Closed by emedvedev** 2019-07-03 01:11 UTC

**Comment by kspook** [comment] 2019-07-03 06:31
@emedvedev,  to prevent from misunderstanding ^^

> Duplicate of #135.
